# Generated by Django 2.2.14 on 2020-11-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizziz',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='NumberQuizziz',
        ),
    ]
