# Generated by Django 2.2.14 on 2020-11-24 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201124_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizziz',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Lesson'),
        ),
    ]
