# Generated by Django 2.2.14 on 2020-11-24 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_quizziz_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizziz',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Lesson'),
        ),
    ]
