# Generated by Django 2.2.14 on 2020-12-04 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201124_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizziz',
            name='number',
        ),
    ]
