# Generated by Django 2.2.14 on 2020-12-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_quizziz_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizziz',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
