# Generated by Django 3.1.7 on 2021-06-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_quizziz_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizziz',
            name='mp3_path',
        ),
        migrations.AddField(
            model_name='quizziz',
            name='highlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizziz',
            name='ipa',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quizziz',
            name='note',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='quizziz',
            name='word',
            field=models.CharField(default='', max_length=255),
        ),
    ]
