# Generated by Django 3.1.7 on 2021-07-09 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210627_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizziz',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.lesson'),
        ),
    ]
