# Generated by Django 2.2.14 on 2020-12-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizziz',
            name='note',
            field=models.CharField(default='', max_length=500),
        ),
    ]
