# Generated by Django 2.2.14 on 2020-12-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimal', '0002_quizziz_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizziz',
            name='note',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
