# Generated by Django 2.2.14 on 2020-12-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimal', '0003_auto_20201225_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizziz',
            name='note',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
