# Generated by Django 2.2.14 on 2020-12-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimal', '0004_auto_20201226_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizziz',
            name='highlight',
            field=models.BooleanField(default=False),
        ),
    ]
