# Generated by Django 2.2.14 on 2020-12-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimal', '0005_quizziz_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizziz',
            name='ipa',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
